id = "vyper"
name = "Vyper"
description = "Vyper language support."
version = "0.0.1"
schema_version = 1
authors = ["Franco <0xpantera@proton.me>"]
repository = "https://github.com/0xpantera/zed-vyper"

[language_servers.vyper-lsp]
name = "Vyper LSP"
languages = ["Vyper"]

[grammars.vyper]
repository = "https://github.com/0xpantera/tree-sitter-vyper-zed"
rev = "f3aab540fc349f52cd5bffc4ce44fd816cdf7bc1"
