id = "vyper"
name = "Vyper"
description = "Vyper language support."
version = "0.0.1"
schema_version = 1
authors = ["Franco <0xpantera@proton.me>"]
repository = "https://github.com/0xpantera/zed-vyper"

[language_servers.vyper-lsp]
name = "Vyper LSP"
languages = ["Vyper"]

[grammars.vyper]
repository = "https://github.com/0xpantera/tree-sitter-vyper-zed"
rev = "feec016d131deff48519a7bd5f1309cd7c3ab7ef"
